# Generated by Django 4.0 on 2023-05-12 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=32, verbose_name='标题')),
                ('permission', models.CharField(max_length=32, verbose_name='权限')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=32, unique=True, verbose_name='角色名')),
                ('permission_id', models.ManyToManyField(to='rbac.Permission', verbose_name='所拥有的的权限')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=32, verbose_name='用户名')),
                ('role_id', models.ManyToManyField(to='rbac.Role', verbose_name='所拥有的的角色')),
            ],
        ),
    ]
